version: '3.7'
services:
  mysql_container:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_manager
      MYSQL_USER: task-manager-user
      MYSQL_PASSWORD: user
    ports:
      - 3306:3306
    volumes:
      - mysql_data_container:/var/lib/mysql

volumes:
  mysql_data_container: